In [ ]:
print("Hello")

Hello

NumPy (Numerical Python) is a powerful library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Think of a NumPy array as a grid of values, all of the same type, indexed by a tuple of non-negative integers. These arrays are much more efficient for storing and manipulating large amounts of numerical data compared to standard Python lists.

Let's start with creating some basic arrays.

### **1. Import NumPy**

In [1]:
import numpy as np

### **2. Basic Array Creation**

In [ ]:
# 1D array from a list of integers
# np.array is used for creating array
arr = np.array([1, 2, 3, 4])
print(arr)

# List with a float, converted to NumPy array
a = [1, 2, 3.5]
print(a)
print(np.array(a)) # NumPy converts all elements to a common data type (float in this case)

[1 2 3 4]
[1, 2, 3.5]
[1.  2.  3.5]

![Screenshot 2025-07-07 123929.png]()
### **Differences between Python Lists and NumPy Arrays**

While both Python lists and NumPy arrays can store collections of data, there are some crucial differences:

1.  **Data Type:** NumPy arrays are designed to handle homogeneous data (all elements are of the same type), which makes numerical operations much more efficient. Python lists can store heterogeneous data types.
2.  **Performance:** NumPy arrays are significantly faster for numerical operations on large datasets compared to Python lists due to their underlying implementation in C and optimized memory usage.
3.  **Functionality:** NumPy provides a vast collection of mathematical functions and operations that can be applied directly to arrays (e.g., element-wise operations, linear algebra). While you can perform similar operations on lists, it often requires loops, which are less efficient.
4.  **Memory Usage:** NumPy arrays are more memory-efficient than Python lists for storing large amounts of numerical data.
5.  **Size Mutability:** Python lists are dynamically sized and can easily grow or shrink. NumPy arrays have a fixed size once created (though you can create new arrays with different sizes).

### **6. Vectors and Matrices**

In NumPy, a **vector** is represented as a 1-dimensional array, and a **matrix** is represented as a 2-dimensional array. NumPy's array structure is ideal for representing these mathematical concepts and performing operations on them efficiently.

#### **Creating Vectors**

In [ ]:
# Creating a vector (1D array)
vector = np.array([1, 2, 3, 4, 5])
print("Vector:")
print(vector)
print("Shape of vector:", vector.shape)

Vector:
[1 2 3 4 5]
Shape of vector: (5,)

#### **Creating Matrices**

In [ ]:
# Creating a matrix (2D array)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix:")
print(matrix)
print("Shape of matrix:", matrix.shape)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of matrix: (3, 3)

### **7. Array Generation Functions**

NumPy provides several functions to create arrays with initial values or sequences.

#### **`np.zeros()`**

Creates an array filled with zeros. You need to specify the shape of the array.

In [ ]:
# Create a 1D array of zeros
zeros_1d = np.zeros(5)
print("1D array of zeros:", zeros_1d)

# Create a 2D array of zeros
zeros_2d = np.zeros((3, 4)) # Shape is specified as a tuple
print("2D array of zeros:\n", zeros_2d)

1D array of zeros: [0. 0. 0. 0. 0.]
2D array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

#### **`np.ones()`**

Creates an array filled with ones. Similar to `np.zeros()`, you specify the shape.

In [ ]:
# Create a 1D array of ones
ones_1d = np.ones(7)
print("1D array of ones:", ones_1d)

# Create a 2D array of ones
ones_2d = np.ones((2, 5))
print("2D array of ones:\n", ones_2d)

#### **`np.arange()`**

Creates an array with a sequence of numbers within a given range. It's similar to Python's built-in `range()` but returns a NumPy array.

In [ ]:
# Create an array from 0 to 9 (exclusive of 10)
range_arr = np.arange(10)
print("Array from arange(10):", range_arr)

# Create an array from 2 to 10 with a step of 2
range_with_step = np.arange(2, 10, 2)
print("Array from arange(2, 10, 2):", range_with_step)

Array from arange(10): [0 1 2 3 4 5 6 7 8 9]
Array from arange(2, 10, 2): [2 4 6 8]

#### **`np.linspace()`**

Creates an array with a specified number of evenly spaced values within a given interval.

In [ ]:
# Create an array of 5 evenly spaced values between 0 and 1
linspace_arr = np.linspace(0, 1, 5)
print("Array from linspace(0, 1, 5):", linspace_arr)

# Create an array of 10 evenly spaced values between 10 and 20
linspace_arr_2 = np.linspace(10, 20, 10)
print("Array from linspace(10, 20, 10):", linspace_arr_2)

Array from linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
Array from linspace(10, 20, 10): [10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]

### **8. Random Number Generation**

NumPy's `random` module is used to generate random numbers and sample from various probability distributions. This is very useful for simulations, statistical analysis, and machine learning.

#### **`np.random.rand()`**

Creates an array of specified shape and fills it with random values from a uniform distribution over `[0, 1)`.

In [ ]:
# Generate a single random number between 0 and 1
random_num = np.random.rand()
print("Single random number:", random_num)

# Generate a 1D array of random numbers
random_arr_1d = np.random.rand(5)
print("1D array of random numbers:", random_arr_1d)

# Generate a 2D array of random numbers
random_arr_2d = np.random.rand(3, 4)
print("2D array of random numbers:\n", random_arr_2d)

Single random number: 0.4520063050603266
1D array of random numbers: [0.55681623 0.28960587 0.34964418 0.45929482 0.68015865]
2D array of random numbers:
 [[0.68967692 0.67642732 0.41201633 0.39914964]
 [0.35273627 0.2004413  0.58424663 0.87276226]
 [0.61826626 0.71806809 0.70628456 0.55414385]]

#### **`np.random.randn()`**

Creates an array of specified shape and fills it with random values from a standard normal distribution (mean 0, variance 1).

In [ ]:
# Generate a single random number from a standard normal distribution
random_normal_num = np.random.randn()
print("Single random number (normal distribution):", random_normal_num)

# Generate a 1D array of random numbers from a standard normal distribution
random_normal_arr_1d = np.random.randn(5)
print("1D array of random numbers (normal distribution):", random_normal_arr_1d)

# Generate a 2D array of random numbers from a standard normal distribution
random_normal_arr_2d = np.random.randn(3, 4)
print("2D array of random numbers (normal distribution):\n", random_normal_arr_2d)

Single random number (normal distribution): 0.7057292075671132
1D array of random numbers (normal distribution): [ 0.25999593 -2.3698012  -0.04522571  0.19672134  0.58049477]
2D array of random numbers (normal distribution):
 [[ 1.28054141 -0.93687926  1.03416373  0.43306981]
 [ 0.2390316  -0.62796753 -0.11915774 -0.01896332]
 [ 0.47305426 -0.05660737 -0.56981181  0.1139892 ]]

#### **`np.random.randint()`**

Creates an array of random integers from a low (inclusive) to high (exclusive) range. You can specify the shape of the array.

In [ ]:
# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_int = np.random.randint(10)
print("Single random integer (0-9):", random_int)

# Generate a 1D array of random integers between 5 (inclusive) and 20 (exclusive)
random_int_arr_1d = np.random.randint(5, 20, 8)
print("1D array of random integers (5-19):", random_int_arr_1d)

# Generate a 2D array of random integers between 100 (inclusive) and 200 (exclusive)
random_int_arr_2d = np.random.randint(100, 200, size=(4, 5))
print("2D array of random integers (100-199):\n", random_int_arr_2d)

Single random integer (0-9): 6
1D array of random integers (5-19): [ 9 14  9 19 14 11 18 11]
2D array of random integers (100-199):
 [[186 141 162 108 195]
 [184 134 164 124 133]
 [108 151 111 128 122]
 [141 133 181 165 190]]

#### **`np.random.choice()`**

Generates a random sample from a given 1-D array (or a sequence).

In [ ]:
# Choose a random element from a list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random_element = np.random.choice(my_list)
print("Random element from list:", random_element)

# Choose multiple random elements with replacement
random_elements_with_replacement = np.random.choice(my_list, size=5, replace=True)
print("Random elements with replacement:", random_elements_with_replacement)

# Choose multiple random elements without replacement
random_elements_without_replacement = np.random.choice(my_list, size=5, replace=False)
print("Random elements without replacement:", random_elements_without_replacement)

# Choose with associated probabilities
elements = ['A', 'B', 'C', 'D']
probabilities = [0.1, 0.2, 0.3, 0.4]
random_element_with_prob = np.random.choice(elements, p=probabilities)
print("Random element with probabilities:", random_element_with_prob)

Random element from list: 2
Random elements with replacement: [8 4 7 7 3]
Random elements without replacement: [6 4 5 9 2]
Random element with probabilities: B

#### **Setting the Random Seed**

For reproducibility, you can set the seed of the random number generator using `np.random.seed()`. This ensures that you get the same sequence of random numbers every time you run the code with the same seed.

In [ ]:
# Set the seed for reproducibility
np.random.seed(42)

# Generate random numbers after setting the seed
random_arr_seed = np.random.rand(5)
print("Random numbers with seed 42 (first run):", random_arr_seed)

# Generate random numbers again with the same seed
np.random.seed(42)
random_arr_seed_again = np.random.rand(5)
print("Random numbers with seed 42 (second run):", random_arr_seed_again)

# Generate random numbers with a different seed
np.random.seed(123)
random_arr_seed_diff = np.random.rand(5)
print("Random numbers with seed 123:", random_arr_seed_diff)

Random numbers with seed 42 (first run): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random numbers with seed 42 (second run): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Random numbers with seed 123: [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]

### **9. Array Attributes**

NumPy arrays have several useful attributes that provide information about their structure and data.

#### **`.shape`**

Returns a tuple representing the dimensions of the array.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr_2d)
print("Shape of array:", arr_2d.shape)

arr_1d = np.array([1, 2, 3, 4, 5])
print("\nArray:", arr_1d)
print("Shape of array:", arr_1d.shape)

Array: [[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)

Array: [1 2 3 4 5]
Shape of array: (5,)

#### **`.ndim`**

Returns the number of dimensions of the array (e.g., 1 for a vector, 2 for a matrix).

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr_2d)
print("Number of dimensions:", arr_2d.ndim)

arr_1d = np.array([1, 2, 3, 4, 5])
print("\nArray:", arr_1d)
print("Number of dimensions:", arr_1d.ndim)

Array: [[1 2 3]
 [4 5 6]]
Number of dimensions: 2

Array: [1 2 3 4 5]
Number of dimensions: 1

#### **`.size`**

Returns the total number of elements in the array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr)
print("Total number of elements:", arr.size)

Array: [[1 2 3]
 [4 5 6]]
Total number of elements: 6

#### **`.dtype`**

Returns the data type of the elements in the array.

In [ ]:
int_arr = np.array([1, 2, 3])
print("Array:", int_arr)
print("Data type:", int_arr.dtype)

float_arr = np.array([1.0, 2.5, 3.1])
print("\nArray:", float_arr)
print("Data type:", float_arr.dtype)

string_arr = np.array(['a', 'b', 'c'])
print("\nArray:", string_arr)
print("Data type:", string_arr.dtype)

Array: [1 2 3]
Data type: int64

Array: [1.  2.5 3.1]
Data type: float64

Array: ['a' 'b' 'c']
Data type: <U1

### **10. Array Methods**

NumPy arrays have numerous methods for performing operations on the array. Here are a few common ones:

#### **`.sum()`**

Returns the sum of all elements in the array. You can also specify an axis to sum along.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Sum of all elements:", arr.sum())
print("Sum along axis 0 (columns):", arr.sum(axis=0))
print("Sum along axis 1 (rows):", arr.sum(axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Sum along axis 0 (columns): [5 7 9]
Sum along axis 1 (rows): [ 6 15]

#### **`.mean()`**

Returns the average of all elements in the array. You can also specify an axis.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Mean of all elements:", arr.mean())
print("Mean along axis 0 (columns):", arr.mean(axis=0))
print("Mean along axis 1 (rows):", arr.mean(axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Mean of all elements: 3.5
Mean along axis 0 (columns): [2.5 3.5 4.5]
Mean along axis 1 (rows): [2. 5.]

#### **`.max()` and `.min()`**

Return the maximum and minimum elements in the array, respectively. You can also specify an axis.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Maximum element:", arr.max())
print("Minimum element:", arr.min())
print("Maximum along axis 0 (columns):", arr.max(axis=0))
print("Minimum along axis 1 (rows):", arr.min(axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Maximum element: 6
Minimum element: 1
Maximum along axis 0 (columns): [4 5 6]
Minimum along axis 1 (rows): [1 4]

#### **`.flatten()`**

Returns a 1-dimensional copy of the array.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print("Original array:\n", arr)
flattened_arr = arr.flatten()
print("Flattened array:", flattened_arr)

Original array:
 [[1 2]
 [3 4]]
Flattened array: [1 2 3 4]

#### **`.reshape()`**

Gives a new shape to an array without changing its data. The new shape must be compatible with the original shape (i.e., the total number of elements must remain the same).

In [ ]:
arr = np.arange(12) # Create a 1D array with 12 elements
print("Original array:", arr)

# Reshape to a 3x4 matrix
reshaped_arr = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_arr)

# Reshape to a 2x6 matrix
reshaped_arr_2 = arr.reshape(2, 6)
print("Reshaped to 2x6:\n", reshaped_arr_2)

# Use -1 to automatically determine a dimension
reshaped_arr_3 = arr.reshape(4, -1) # Reshape to 4 rows, automatically determine columns
print("Reshaped to 4x (automatic columns):\n", reshaped_arr_3)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Reshaped to 4x (automatic columns):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

#### **`np.resize()`**

Creates a new array with the specified shape. If the new array is larger than the original, the new elements are filled with copies of the original array's elements. If the new array is smaller, the elements are taken from the beginning of the original array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)

# Resize to a larger array
resized_larger = np.resize(arr, (8,))
print("Resized to larger (8 elements):", resized_larger)

# Resize to a smaller array
resized_smaller = np.resize(arr, (4,))
print("Resized to smaller (4 elements):", resized_smaller)

# Resize to a 2D array
resized_2d = np.resize(arr, (3, 3))
print("Resized to 2D (3x3):\n", resized_2d)

Original array: [1 2 3 4 5 6]
Resized to larger (8 elements): [1 2 3 4 5 6 1 2]
Resized to smaller (4 elements): [1 2 3 4]
Resized to 2D (3x3):
 [[1 2 3]
 [4 5 6]
 [1 2 3]]

### **12. Indexing and Slicing**

Indexing and slicing are fundamental ways to access and manipulate elements within NumPy arrays.

#### **Indexing 1D Arrays (Vectors)**

You can access individual elements of a 1D array using their index (position), starting from 0.

In [ ]:
vector = np.array([10, 20, 30, 40, 50])
print("Vector:", vector)

# Accessing a single element
print("Element at index 0:", vector[0])
print("Element at index 3:", vector[3])

# Negative indexing (from the end of the array)
print("Last element:", vector[-1])
print("Second to last element:", vector[-2])

Vector: [10 20 30 40 50]
Element at index 0: 10
Element at index 3: 40
Last element: 50
Second to last element: 40

#### **Slicing 1D Arrays (Vectors)**

Slicing allows you to extract a portion (a sub-array) of a 1D array. The syntax is `[start:stop:step]`, where:
- `start`: The starting index (inclusive). If omitted, it defaults to 0.
- `stop`: The ending index (exclusive). If omitted, it defaults to the end of the array.
- `step`: The step size between elements. If omitted, it defaults to 1.

In [ ]:
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Vector:", vector)

# Get elements from index 2 to 5 (exclusive of 5)
print("Slice from index 2 to 5:", vector[2:5])

# Get elements from the beginning to index 4 (exclusive of 4)
print("Slice from beginning to index 4:", vector[:4])

# Get elements from index 6 to the end
print("Slice from index 6 to the end:", vector[6:])

# Get every second element
print("Slice with step of 2:", vector[::2])

# Get elements from index 1 to 8 with a step of 3
print("Slice from 1 to 8 with step 3:", vector[1:8:3])

# Reverse the array using slicing
print("Reversed vector:", vector[::-1])

Vector: [0 1 2 3 4 5 6 7 8 9]
Slice from index 2 to 5: [2 3 4]
Slice from beginning to index 4: [0 1 2 3]
Slice from index 6 to the end: [6 7 8 9]
Slice with step of 2: [0 2 4 6 8]
Slice from 1 to 8 with step 3: [1 4 7]
Reversed vector: [9 8 7 6 5 4 3 2 1 0]

#### **Indexing 2D Arrays (Matrices)**

For 2D arrays, you use a comma-separated tuple of indices to access elements, where the first index refers to the row and the second to the column: `[row_index, column_index]`.

In [ ]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print("Matrix:\n", matrix)

# Accessing a single element
print("Element at row 0, column 1:", matrix[0, 1])
print("Element at row 2, column 2:", matrix[2, 2])

# Using negative indexing
print("Element at last row, last column:", matrix[-1, -1])

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 0, column 1: 20
Element at row 2, column 2: 90
Element at last row, last column: 90

#### **Slicing 2D Arrays (Matrices)**

Slicing in 2D works similarly to 1D, but you apply it to both dimensions, separated by a comma: `[row_slice, column_slice]`.

In [ ]:
matrix = np.array([[ 0,  1,  2,  3],
                   [10, 11, 12, 13],
                   [20, 21, 22, 23],
                   [30, 31, 32, 33]])
print("Matrix:\n", matrix)

# Get the first row
print("First row:", matrix[0, :])
print("First row (another way):", matrix[0]) # If you omit the column slice, it selects the whole row

# Get the second column
print("Second column:", matrix[:, 1])

# Get a sub-matrix (rows 1 to 3, columns 0 to 2)
print("Sub-matrix (rows 1-2, columns 0-1):\n", matrix[1:3, 0:2])

# Get elements from every second row
print("Every second row:\n", matrix[::2, :])

# Get elements from every second column
print("Every second column:\n", matrix[:, ::2])

# Get a sub-matrix with steps
print("Sub-matrix with steps (rows 0-3, step 2; columns 1-4, step 2):\n", matrix[0:3:2, 1:4:2])

Matrix:
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
First row: [0 1 2 3]
First row (another way): [0 1 2 3]
Second column: [ 1 11 21 31]
Sub-matrix (rows 1-2, columns 0-1):
 [[10 11]
 [20 21]]
Every second row:
 [[ 0  1  2  3]
 [20 21 22 23]]
Every second column:
 [[ 0  2]
 [10 12]
 [20 22]
 [30 32]]
Sub-matrix with steps (rows 0-3, step 2; columns 1-4, step 2):
 [[ 1  3]
 [21 23]]

#### **Boolean Indexing**

You can use a boolean array of the same shape as the original array to select elements where the boolean array is `True`.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

# Create a boolean array
boolean_index = np.array([True, False, True, False, True])

# Select elements using the boolean array
print("Elements selected by boolean index:", arr[boolean_index])

# Select elements based on a condition
print("Elements greater than 30:", arr[arr > 30])

Array: [10 20 30 40 50]
Elements selected by boolean index: [10 30 50]
Elements greater than 30: [40 50]

## Arithmetic operations

In [ ]:
# 1. Create two sample NumPy arrays of the same shape
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# 2. Perform element-wise addition
addition_result = arr1 + arr2
print("\nElement-wise addition:\n", addition_result)

# 3. Perform element-wise subtraction
subtraction_result = arr1 - arr2
print("\nElement-wise subtraction:\n", subtraction_result)

# 4. Perform element-wise multiplication
multiplication_result = arr1 * arr2
print("\nElement-wise multiplication:\n", multiplication_result)

# 5. Perform element-wise division
# Be mindful of potential division by zero if arr2 contains zeros.
# Using astype(float) to ensure float division.
division_result = arr1 / arr2.astype(float)
print("\nElement-wise division:\n", division_result)

# 6. Perform element-wise exponentiation
exponentiation_result = arr1 ** arr2
print("\nElement-wise exponentiation:\n", exponentiation_result)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Element-wise addition:
 [[ 6  8]
 [10 12]]

Element-wise subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Element-wise division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Element-wise exponentiation:
 [[    1    64]
 [ 2187 65536]]

## Broadcasting

In [ ]:
# 1. Create a NumPy array (2x3 matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix:\n", matrix)

# 2. Create a smaller NumPy array (1D array with 3 elements)
vector_compatible = 10
print("\nCompatible Vector:", vector_compatible)

# 3. Perform an arithmetic operation (addition) between the matrix and the compatible 1D array
addition_result_compatible = matrix + vector_compatible
print("\nMatrix + Compatible Vector (Broadcasting):\n", addition_result_compatible)
print("Explanation: Broadcasting adds each element of the vector to the corresponding column of the matrix.")

# 4. Create a 1D array with 2 elements
vector_incompatible = np.array([100, 200])
print("\nIncompatible Vector:", vector_incompatible)

# 5. Perform an arithmetic operation (addition) between the matrix and the new 1D array
try:
    addition_result_incompatible = matrix + vector_incompatible
    print("\nMatrix + Incompatible Vector (Broadcasting):\n", addition_result_incompatible)
except ValueError as e:
    print(f"\nError when adding Matrix and Incompatible Vector: {e}")
    print("Explanation: Broadcasting failed because the dimensions of the matrix (2, 3) and the vector (2,) are not compatible.")
    print("For broadcasting to work, the dimensions must either be equal, one of them must be 1, or one of them must not exist.")

Matrix:
 [[1 2 3]
 [4 5 6]]

Compatible Vector: 10

Matrix + Compatible Vector (Broadcasting):
 [[11 12 13]
 [14 15 16]]
Explanation: Broadcasting adds each element of the vector to the corresponding column of the matrix.

Incompatible Vector: [100 200]

Error when adding Matrix and Incompatible Vector: operands could not be broadcast together with shapes (2,3) (2,)
Explanation: Broadcasting failed because the dimensions of the matrix (2, 3) and the vector (2,) are not compatible.
For broadcasting to work, the dimensions must either be equal, one of them must be 1, or one of them must not exist.

## Deep and shallow copy

### Subtask:
Learn the difference between deep and shallow copies of NumPy arrays and how to create them.

**Reasoning**:
The subtask requires creating a NumPy array, creating both shallow and deep copies, modifying the copies, and observing the effects on the original array. This can be achieved with a single code block.

In [ ]:
# 1. Create a NumPy array named original_array.
original_array = np.array([1, 2, 3, 4, 5])
print("Original array:", original_array)

# 2. Create a shallow copy of original_array using the assignment operator (=). Name it shallow_copy.
shallow_copy = original_array
print("Shallow copy (initial):", shallow_copy)

# 3. Modify an element in shallow_copy and observe if the change is reflected in original_array. Print both arrays to show the effect.
shallow_copy[0] = 99
print("\nModified shallow copy:", shallow_copy)
print("Original array after modifying shallow copy:", original_array)
print("Observation: Modifying the shallow copy *does* affect the original array because they reference the same underlying data.")

# 4. Create a deep copy of original_array using the .copy() method. Name it deep_copy.
deep_copy = original_array.copy()
print("\nDeep copy (initial):", deep_copy)

# 5. Modify an element in deep_copy and observe if the change is reflected in original_array. Print both arrays to show the effect.
deep_copy[0] = 100
print("Modified deep copy:", deep_copy)
print("Original array after modifying deep copy:", original_array)
print("Observation: Modifying the deep copy *does not* affect the original array because it is a separate copy of the data.")

Original array: [1 2 3 4 5]
Shallow copy (initial): [1 2 3 4 5]

Modified shallow copy: [99  2  3  4  5]
Original array after modifying shallow copy: [99  2  3  4  5]
Observation: Modifying the shallow copy *does* affect the original array because they reference the same underlying data.

Deep copy (initial): [99  2  3  4  5]
Modified deep copy: [100   2   3   4   5]
Original array after modifying deep copy: [99  2  3  4  5]
Observation: Modifying the deep copy *does not* affect the original array because it is a separate copy of the data.

## Matrix operations

### Subtask:
Cover common matrix operations like multiplication and transpose.

**Reasoning**:
The subtask requires creating matrices for multiplication, performing the multiplication, creating another matrix for transposition, and performing the transposition. These steps can be grouped into a single code block.

In [ ]:
# 1. Create two NumPy arrays, matrix_a and matrix_b, suitable for matrix multiplication.
# matrix_a is 2x3
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])

# matrix_b is 3x2 (number of columns in matrix_a equals number of rows in matrix_b)
matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

print("Matrix A:\n", matrix_a)
print("Shape of Matrix A:", matrix_a.shape)
print("\nMatrix B:\n", matrix_b)
print("Shape of Matrix B:", matrix_b.shape)

# 2. Perform matrix multiplication of matrix_a and matrix_b.
# Using the @ operator (preferred for matrix multiplication in NumPy)
matrix_product_at = matrix_a @ matrix_b
print("\nMatrix A @ Matrix B (using @ operator):\n", matrix_product_at)

# Using np.dot()
matrix_product_dot = np.dot(matrix_a, matrix_b)
print("Matrix A . Matrix B (using np.dot()):\n", matrix_product_dot)


# 3. Create a NumPy array, matrix_c.
matrix_c = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("\nMatrix C:\n", matrix_c)
print("Shape of Matrix C:", matrix_c.shape)

# 4. Compute the transpose of matrix_c.
# Using the .T attribute
matrix_c_transpose_attr = matrix_c.T
print("\nTranspose of Matrix C (using .T attribute):\n", matrix_c_transpose_attr)
print("Shape of Transpose of Matrix C:", matrix_c_transpose_attr.shape)

# Using np.transpose()
matrix_c_transpose_func = np.transpose(matrix_c)
print("Transpose of Matrix C (using np.transpose()):\n", matrix_c_transpose_func)
print("Shape of Transpose of Matrix C:", matrix_c_transpose_func.shape)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Shape of Matrix A: (2, 3)

Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Shape of Matrix B: (3, 2)

Matrix A @ Matrix B (using @ operator):
 [[ 58  64]
 [139 154]]
Matrix A . Matrix B (using np.dot()):
 [[ 58  64]
 [139 154]]

Matrix C:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of Matrix C: (3, 4)

Transpose of Matrix C (using .T attribute):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape of Transpose of Matrix C: (4, 3)
Transpose of Matrix C (using np.transpose()):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape of Transpose of Matrix C: (4, 3)

## Advanced array manipulation

### Subtask:
Explore more advanced techniques for manipulating array shapes and elements.

**Reasoning**:
The subtask requires creating, reshaping, flattening, raveling, swapping axes, and moving axes of NumPy arrays. These steps involve fundamental array manipulation techniques in NumPy. I will create a single code block to perform these operations sequentially as requested by the instructions.

## Stacking arrays

### Subtask:
Learn how to combine multiple arrays into a single larger array.

**Reasoning**:
The subtask requires demonstrating how to stack NumPy arrays both vertically and horizontally. This can be achieved by creating sample arrays and using `np.vstack()` and `np.hstack()`.

## Stacking arrays

### Subtask:
Learn how to combine multiple arrays into a single larger array.

**Reasoning**:
The subtask requires demonstrating how to stack NumPy arrays both vertically and horizontally. This can be achieved by creating sample arrays and using `np.vstack()` and `np.hstack()`.

In [ ]:
# 1. Create two sample NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

# 2. Stack the arrays vertically (row-wise) using np.vstack()
# The arrays must have the same number of columns.
vstacked_arr = np.vstack((arr1, arr2))
print("\nVertically stacked array (vstack):\n", vstacked_arr)

# 3. Create two more sample NumPy arrays for horizontal stacking
arr3 = np.array([[1], [2]])
arr4 = np.array([[3], [4]])

print("\nArray 3:\n", arr3)
print("Array 4:\n", arr4)

# 4. Stack the arrays horizontally (column-wise) using np.hstack()
# The arrays must have the same number of rows.
hstacked_arr = np.hstack((arr3, arr4))
print("\nHorizontally stacked array (hstack):\n", hstacked_arr)

# 5. Demonstrate stacking with more dimensions
arr5 = np.arange(6).reshape(2, 3)
arr6 = np.arange(6, 12).reshape(2, 3)

print("\nArray 5:\n", arr5)
print("Array 6:\n", arr6)

# Vertical stacking of 2D arrays
vstacked_2d = np.vstack((arr5, arr6))
print("\nVertically stacked 2D arrays (vstack):\n", vstacked_2d)

# Horizontal stacking of 2D arrays
hstacked_2d = np.hstack((arr5, arr6))
print("Horizontally stacked 2D arrays (hstack):\n", hstacked_2d)

Array 1: [1 2 3]
Array 2: [4 5 6]

Vertically stacked array (vstack):
 [[1 2 3]
 [4 5 6]]

Array 3:
 [[1]
 [2]]
Array 4:
 [[3]
 [4]]

Horizontally stacked array (hstack):
 [[1 3]
 [2 4]]

Array 5:
 [[0 1 2]
 [3 4 5]]
Array 6:
 [[ 6  7  8]
 [ 9 10 11]]

Vertically stacked 2D arrays (vstack):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Horizontally stacked 2D arrays (hstack):
 [[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]

## Splitting arrays

### Subtask:
Understand how to divide a single array into multiple smaller arrays.

**Reasoning**:
The subtask requires demonstrating how to split NumPy arrays horizontally and vertically. This can be achieved by creating a sample array and using `np.hsplit()` and `np.vsplit()`.

In [ ]:
# 1. Create a sample NumPy array
arr = np.arange(16).reshape(4, 4)
print("Original array:\n", arr)

# 2. Split the array horizontally (column-wise) into 2 equal parts using np.hsplit()
# The array must be divisible along the horizontal axis.
hsplit_arrs = np.hsplit(arr, 2)
print("\nHorizontally split into 2 parts:\n", hsplit_arrs)

# 3. Split the array horizontally at specific indices
hsplit_indices = np.hsplit(arr, [1, 3])
print("\nHorizontally split at indices [1, 3]:\n", hsplit_indices)

# 4. Split the array vertically (row-wise) into 4 equal parts using np.vsplit()
# The array must be divisible along the vertical axis.
vsplit_arrs = np.vsplit(arr, 4)
print("\nVertically split into 4 parts:\n", vsplit_arrs)

# 5. Split the array vertically at specific indices
vsplit_indices = np.vsplit(arr, [1, 3])
print("\nVertically split at indices [1, 3]:\n", vsplit_indices)

# 6. Using np.array_split() for unequal splits
arr_unequal = np.arange(10)
print("\nOriginal array (unequal split):\n", arr_unequal)
unequal_split = np.array_split(arr_unequal, 3) # Split into 3 parts (unequal)
print("Unequally split into 3 parts:\n", unequal_split)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontally split into 2 parts:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

Horizontally split at indices [1, 3]:
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]

Vertically split into 4 parts:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

Vertically split at indices [1, 3]:
 [array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

Original array (unequal split):
 [0 1 2 3 4 5 6 7 8 9]
Unequally split into 3 parts:
 [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Valid Sudoku

In [9]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

b = s.sum(axis=0)
for i in b:
  if i !=45:
    print("Sudoku is not valid")
    break
else:
  print("Sudoku is valid")

c = s.sum(axis=0)
for i in c:
  if i !=45:
    print("Sudoku is not valid")
    break
else:
  print("Sudoku is valid")

for i in range(0,9,3):
  for j in range(0,9,3):
    print(d.sum())

Sudoku is valid
Sudoku is valid
45
45
45
45
45
45
45
45
45

General Questions

In [55]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [56]:
# Get the shape of the matrix.
# print(data.shape)
# Find the average age of students.
# print(np.mean(data[:,0]))
# Calculate the average marks in each subject.
# print(np.mean(data[:,1:],axis=0))
# Find the highest marks in Math.
# print(np.max(data[:,1]))
# Extract Math marks of all students.
# print(data[:,2])
# Find the highest Science mark.
# np.max(data[:,2])
# Get details of the student who scored more than 90 in Math.
# print(data[data[: ,1] >= 90])
# Increase Math marks of all students by 5.
# data[:,1] += 5
# print(data)
# Find how many students are younger than 19.
# print(len(data[data[:,0] <19]))
# Calculate the average marks in each subject (column-wise mean).
# print(np.mean(data[:,1:],axis=0))
# Get data of students who scored at least 80 in both subjects.
# print(data[(data[:,1] >= 80) & (data[:,2] >= 80)])
# Replace all Science marks < 75 with 0.
# data[:,2][data[:,2] < 75] = 0
# print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]